<<<<<<< HEAD
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
=======
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
>>>>>>> 920aea0ab65ee18c3c6889c75023fc25561a852b
    path: /api/login_check