<<<<<<< HEAD
_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix: /_error
=======
_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix: /_error
>>>>>>> 920aea0ab65ee18c3c6889c75023fc25561a852b
