<<<<<<< HEAD
controllers:
    resource: ../../src/Controller/
    type: annotation
=======
controllers:
    resource: ../../src/Controller/
    type: annotation
>>>>>>> 920aea0ab65ee18c3c6889c75023fc25561a852b
