<<<<<<< HEAD
easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin
    type: annotation
=======
easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin
    type: annotation
>>>>>>> 920aea0ab65ee18c3c6889c75023fc25561a852b
