<<<<<<< HEAD
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
=======
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
>>>>>>> 920aea0ab65ee18c3c6889c75023fc25561a852b
