<<<<<<< HEAD
framework:
    router:
        strict_requirements: ~
        utf8: true
=======
framework:
    router:
        strict_requirements: ~
        utf8: true
>>>>>>> 920aea0ab65ee18c3c6889c75023fc25561a852b
