<<<<<<< HEAD
web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler: { only_exceptions: false }
=======
web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler: { only_exceptions: false }
>>>>>>> 920aea0ab65ee18c3c6889c75023fc25561a852b
